name: CPBuild

on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [linux, windows, macos]
        include:
          - name: linux
            os: ubuntu-latest
          - name: windows
            os: windows-latest
          - name: macos
            os: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: symbitic/install-cmake@master

      - name: CMakePrep
        run: cmake -Bbuild .

      - name: Build
        run: cmake --build build --config Release

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
            type: 'zip'
            filename: 'release.zip'
            path: 'build/*'
            exclusions: 'build/CMakeCache.txt build/cmake_install.cmake build/CMakeFiles/* build/Makefile'

      - uses: actions/upload-artifact@v2
        with:
            name: release-${{ matrix.os }}
            path: release.zip
